version: '3.9'

services:
  balancer:
    build: ./load_balancer
    image: balancer-image
    container_name: balancer
    privileged: true
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      net1:
        aliases:
          - balancer

  server-template:
    build: ./server
    image: server-image
    environment:
      - SERVER_ID=template
    networks:
      net1:
        aliases:
          - server-template
    deploy:
      replicas: 0  # Prevents it from auto-starting
    entrypoint: ["sleep", "infinity"]  # Template container doesn't run Flask
    profiles:
      - do-not-start

networks:
  net1:
