version: "3.9"
services:
  loadbalancer:
    build: ./load_balancer
    container_name: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - loadbalancer
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build: ./server
    container_name: server1
    networks:
      net1:
        aliases:
          - server1
    environment:
      - SERVER_ID=1

  server2:
    build: ./server
    container_name: server2
    networks:
      net1:
        aliases:
          - server2
    environment:
      - SERVER_ID=2

  server3:
    build: ./server
    container_name: server3
    networks:
      net1:
        aliases:
          - server3
    environment:
      - SERVER_ID=3

networks:
  net1:
    driver: bridge
